version: '3.2'

services:
  api:
    image: iil3i/api-proxy:0.0.1.pre-release-3
    environment:
      - V1_UPSTREAM=foo_service_v1
      - V2_UPSTREAM=foo_service_v2
      - V3_UPSTREAM=foo_service_v3
    volumes:
      - ./services.yaml.tmpl:/services.yaml.tmpl
    ports:
      - "1731:80"
  foo_service_v1:
    image: nginxdemos/hello:plain-text
  foo_service_v2:
    image: nginxdemos/hello:plain-text
  foo_service_v3:
    image: nginxdemos/hello:plain-text

