version: '3.2'

services:
  api:
    image: iil3i/api-proxy:latest
    environment:
      - V1_UPSTREAMS=foo_service_v1_u1 foo_service_v1_u2 foo_service_v1_u3
      - V2_UPSTREAMS=foo_service_v2_u1 foo_service_v2_u2 foo_service_v2_u3
      - V3_UPSTREAMS=foo_service_v3_u1 foo_service_v3_u2 foo_service_v3_u3
    volumes:
      - ./services.yaml.tmpl:/services.yaml.tmpl
    ports:
      - "1731:80"

  foo_service_v1_u1:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v1_u1
  foo_service_v1_u2:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v1_u2
  foo_service_v1_u3:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v1_u3

  foo_service_v2_u1:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v2_u1
  foo_service_v2_u2:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v2_u2
  foo_service_v2_u3:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v2_u3

  foo_service_v3_u1:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v3_u1
  foo_service_v3_u2:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v3_u2
  foo_service_v3_u3:
    image: nginxdemos/hello:plain-text
    environment:
    - MSG=foo v3_u3
